name: SOL Price Notifier

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes (GitHub's minimum reliable cadence)
  workflow_dispatch:        # allow manual run

permissions:
  contents: write           # so we can update state.json in the repo

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run notifier
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python sol_notifier.py

      - name: Commit state if changed
        run: |
          if [[ `git status --porcelain` ]]; then
            git config user.name "sol-bot"
            git config user.email "sol-bot@users.noreply.github.com"
            git add state.json
            git commit -m "[skip ci] update state"
            git push
          fi
